sudo: false
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "iojs-1"
  - "iojs-2"
  - "iojs-3"
notifications:
  email:
    - rod@vagg.org
before_install:
  - npm install npm
  - mv node_modules npm
  - npm/.bin/npm --version
  - CXX --version
  - npm/.bin/npm install
  - if [[ $(node -v | sed 's/v\([0-9][0-9]*\.[0-9][0-9]*\)\.[0-9][0-9]*/\1/') == "0.8" ]]; then node_modules/.bin/node-gyp rebuild --directory test; else node_modules/.bin/pangyp rebuild --directory test; fi
install:
script: tap --gc test/js/*-test.js
nstall:
script: tap --gc test/js/*-test.js
